In [1]:
import pandas as pd
from sqlalchemy import create_engine
import pymysql

In [2]:
pd.set_option('display.max_colwidth', None)

## Read in the files

In [3]:
works = pd.read_csv("./Data/goodreads_works.csv")
reviews = pd.read_csv("./Data/goodreads_reviews.csv", low_memory=False)

### Process the works file

In [4]:
works.head()

,work_id,isbn,isbn13,original_title,author,original_publication_year,num_pages,description,genres,image_url,reviews_count,text_reviews_count,5_star_ratings,4_star_ratings,3_star_ratings,2_star_ratings,1_star_ratings,ratings_count,avg_rating,similar_books
0,2919130,1416534601,9.781417e+12,Nocturnes,John Connolly,2004.0,NaN,NaN,"fiction, fantasy, paranormal, mystery, thriller, crime, young-adult",https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png,8820,338,1118,1601,1029,190,58,3996,3.9,NaN
1,52087333,NaN,NaN,Draw Play,Tia Lewis,2016.0,NaN,"Jake:\nI can't believe my coach assigned me a tutor. I'm all that on the field and between the sheets -- who cares about my stupid grades?\nBut Claire doesn't treat me like I'm dumb. When we're not busy fighting, she actually encourages me. And with those sexy curves of hers, I know just how to thank her.\nClaire:\nI hate football players, but I need the money. Jake is just as cocky and arrogant as the worst of them ... but his touch sets me on fire.\nI have to believe he's different, that he won't use me and break my heart. Because I can't stop wanting him. I just hope I survive the ride.","romance, fiction",https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png,2482,204,204,353,274,77,29,937,3.7,NaN
2,1649583,1416505520,9.781417e+12,Citizen of the Galaxy,Robert A. Heinlein,1957.0,NaN,"In a distant galaxy, the atrocity of slavery was alive and well, and young Thorby was just another orphaned boy sold at auction. But his new owner, Baslim, is not the disabled beggar he appears to be: adopting Thorby as his son, he fights relentlessly as an abolitionist spy. When the authorities close in on Baslim, Thorby must ride with the Free Traders a league of merchant princes throughout the many worlds of a hostile galaxy, finding the courage to live by his wits and fight his way from society's lowest rung. But Thorby's destiny will be forever changed when he discovers the truth about his own identity...","fiction, young-adult, fantasy, paranormal, children",https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png,16506,447,3539,4351,2863,444,53,11250,4.0,NaN
3,688299,0060541830,9.780061e+12,Congo,Michael Crichton,1980.0,NaN,"Deep in the African rain forest, near the legendary ruins of the Lost City of Zinj, an expedition of eight American geologists is mysteriously and brutally killed in a matter of minutes.\nTen thousand miles away, Karen Ross, the Congo Project Supervisor, watches a gruesome video transmission of the aftermath: a camp destroyed, tents crushed and torn, equipment scattered in the mud alongside dead bodies -- all motionless except for one moving image -- a grainy, dark, man-shaped blur.\nIn San Francisco, primatologist Peter Elliot works with Amy, a gorilla with an extraordinary vocabulary of 620 ""signs,"" the most ever learned by a primate, and she likes to fingerpaint. But recently, her behavior has been erratic and her drawings match, with stunning accuracy, the brittle pages of a Portuguese print dating back to 1642 . . . a drawing of an ancient lost city. A new expedition -- along with Amy -- is sent into the Congo where they enter a secret world, and the only way out may be through a horrifying death . . .","fiction, mystery, thriller, crime, fantasy, paranormal",https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png,170916,1633,25081,45775,48505,14001,2926,136288,3.6,NaN
4,3464264,0451528824,9.780452e+12,Anne of Green Gables,L.M. Montgomery,1908.0,NaN,"Everyone's favorite redhead, the spunky Anne Shirley, begins her adventures at Green Gables, a farm outside Avonlea, Prince Edward Island. When the freckled girl realizes that the elderly Cuthberts wanted to adopt a boy instead, she begins to try to win them and, consequently, the reader, over.","fiction, young-adult, children, history, historical fiction, biography, romance",https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png,743392,14586,272952,161856,81578,19933,9099,545418,4.2,NaN

## Fix the column Data Types

In [5]:
works.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13525 entries, 0 to 13524
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   work_id                    13525 non-null  int64
 1   isbn                       11474 non-null  object
 2   isbn13                     11864 non-null  float64
 3   original_title             13525 non-null  object
 4   author                     13525 non-null  object
 5   original_publication_year  13507 non-null  float64
 6   num_pages                  12795 non-null  float64
 7   description                13356 non-null  object
 8   genres                     13525 non-null  object
 9   image_url                  13525 non-null  object
 10  reviews_count              13525 non-null  int64
 11  text_reviews_count         13525 non-null  int64
 12  5_star_ratings             13525 non-null  int64
 13  4_star_ratings             13525 non-null  int64
 14  3_star_ratings             13525 non-null  int64
 15  2_star_ratings             13525 non-null  int64
 16  1_star_ratings             13525 non-null  int64
 17  ratings_count              13525 non-null  int64
 18  avg_rating                 13525 non-null  float64
 19  similar_books              11010 non-null  object
dtypes: float64(4), int64(9), object(7)
memory usage: 2.1+ MB

In [6]:
# Here we convert some columns to integer and string values and fill missing values with 0 
# This solves an error when casting a type with missing values

works['original_publication_year'] = pd.to_numeric(works['original_publication_year'], errors='coerce').fillna(0).astype(int)
works['num_pages'] = pd.to_numeric(works['num_pages'], errors='coerce').fillna(0).astype(int)
works['isbn13'] = works['isbn13'].astype('string')

In [7]:
works.dtypes

work_id                               int64
isbn                                 object
isbn13                       string[python]
original_title                       object
author                               object
original_publication_year             int64
num_pages                             int64
description                          object
genres                               object
image_url                            object
reviews_count                         int64
text_reviews_count                    int64
5_star_ratings                        int64
4_star_ratings                        int64
3_star_ratings                        int64
2_star_ratings                        int64
1_star_ratings                        int64
ratings_count                         int64
avg_rating                          float64
similar_books                        object
dtype: object

In [8]:
# Remove the decimal point from the converted isbn13 column
works['isbn13'] =works['isbn13'].str.replace(".0","", regex=False)
works.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13525 entries, 0 to 13524
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   work_id                    13525 non-null  int64
 1   isbn                       11474 non-null  object
 2   isbn13                     11864 non-null  string
 3   original_title             13525 non-null  object
 4   author                     13525 non-null  object
 5   original_publication_year  13525 non-null  int64
 6   num_pages                  13525 non-null  int64
 7   description                13356 non-null  object
 8   genres                     13525 non-null  object
 9   image_url                  13525 non-null  object
 10  reviews_count              13525 non-null  int64
 11  text_reviews_count         13525 non-null  int64
 12  5_star_ratings             13525 non-null  int64
 13  4_star_ratings             13525 non-null  int64
 14  3_star_ratings             13525 non-null  int64
 15  2_star_ratings             13525 non-null  int64
 16  1_star_ratings             13525 non-null  int64
 17  ratings_count              13525 non-null  int64
 18  avg_rating                 13525 non-null  float64
 19  similar_books              11010 non-null  object
dtypes: float64(1), int64(11), object(7), string(1)
memory usage: 2.1+ MB

In [9]:
# Before we start we will fill missing values with a blank string.
works['description'] = works['description'].fillna('')

## Perform Sentiment Analysis
We will do both a VADER Sentiment Analysis and a HuggingFace Sentiment Analysis

In [10]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [11]:
%%time
# Create Vader Sentiment Score
analyzer=SentimentIntensityAnalyzer()

# define a function to get the score
def get_sentiment(text):
    return analyzer.polarity_scores(text)['compound']

CPU times: total: 15.6 ms
Wall time: 18.5 ms

In [12]:
# apply the function
works['sentiment'] = works['description'].apply(get_sentiment)

In [13]:
%%time
# Now do a sentiment analysis using NLP

from transformers import pipeline, logging

logging.set_verbosity_error() # Turn off logging except for major errors

sentiment_analyzer = pipeline("sentiment-analysis",
                              model="distilbert/distilbert-base-uncased-finetuned-sst-2-english",
                              device='cuda', # Use GPU
                              force_download=True,
                              truncation=True) # adding truncation here to truncate text before analyzing sentiment

sentiment_scores = works['description'].apply(sentiment_analyzer) # Apply the Analyser

# extract the label and score and create a sentiment score for all books
works['label_hf'] = sentiment_scores.apply(lambda x: x[0]['label'])
works['score_hf'] = sentiment_scores.apply(lambda x: x[0]['score'])

# This applys a negative value for a negative sentiment
works['sentiment_hf'] = works.apply(lambda row: row['score_hf'] if row['label_hf'] == 'POSITIVE' else -row['score_hf'], axis=1)

C:\Users\andrew\anaconda3\envs\nlp_transformers\Lib\site-packages\huggingface_hub\file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

CPU times: total: 3min 56s
Wall time: 4min 2s

## Now write the data frame to the SQL Server

In [14]:
engine = create_engine('mysql+pymysql://root:$H0nggh0ri*@localhost:3306/mavenbookshelf')

In [15]:
works.to_sql('works', con=engine, if_exists='replace', index=False)

13525

## Try emotion analysis on works

In [16]:
%%time
from transformers import pipeline

# Load emotion classification pipeline
emotion_pipeline = pipeline(
    "text-classification",
    model="j-hartmann/emotion-english-distilroberta-base",
    tokenizer="j-hartmann/emotion-english-distilroberta-base",
    force_download=True,
    top_k=None,
    truncation=True,
    max_length=512
)


# Apply to your dataset
def get_emotion_scores(text):
    scores = emotion_pipeline(text)[0]
    return {item['label']: item['score'] for item in scores}

works['emotion_scores'] = works['description'].apply(get_emotion_scores)

C:\Users\andrew\anaconda3\envs\nlp_transformers\Lib\site-packages\huggingface_hub\file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

CPU times: total: 1h 13min 32s
Wall time: 1h 8min 31s

In [17]:
works.head()

,work_id,isbn,isbn13,original_title,author,original_publication_year,num_pages,description,genres,image_url,...,2_star_ratings,1_star_ratings,ratings_count,avg_rating,similar_books,sentiment,label_hf,score_hf,sentiment_hf,emotion_scores
0,2919130,1416534601,9781416534600,Nocturnes,John Connolly,2004,0,,"fiction, fantasy, paranormal, mystery, thriller, crime, young-adult",https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png,...,190,58,3996,3.9,NaN,0.0000,POSITIVE,0.748121,0.748121,"{'neutral': 0.5494771599769592, 'sadness': 0.11169011145830154, 'disgust': 0.10400661081075668, 'surprise': 0.07876542210578918, 'anger': 0.06413354724645615, 'fear': 0.05136276036500931, 'joy': 0.04056437686085701}"
1,52087333,NaN,<NA>,Draw Play,Tia Lewis,2016,0,"Jake:\nI can't believe my coach assigned me a tutor. I'm all that on the field and between the sheets -- who cares about my stupid grades?\nBut Claire doesn't treat me like I'm dumb. When we're not busy fighting, she actually encourages me. And with those sexy curves of hers, I know just how to thank her.\nClaire:\nI hate football players, but I need the money. Jake is just as cocky and arrogant as the worst of them ... but his touch sets me on fire.\nI have to believe he's different, that he won't use me and break my heart. Because I can't stop wanting him. I just hope I survive the ride.","romance, fiction",https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png,...,77,29,937,3.7,NaN,-0.5726,POSITIVE,0.998970,0.998970,"{'anger': 0.5609580278396606, 'disgust': 0.2903720438480377, 'surprise': 0.0513620562851429, 'neutral': 0.050355006009340286, 'sadness': 0.02084539830684662, 'fear': 0.017771592363715172, 'joy': 0.008335777558386326}"
2,1649583,1416505520,9781416505525,Citizen of the Galaxy,Robert A. Heinlein,1957,0,"In a distant galaxy, the atrocity of slavery was alive and well, and young Thorby was just another orphaned boy sold at auction. But his new owner, Baslim, is not the disabled beggar he appears to be: adopting Thorby as his son, he fights relentlessly as an abolitionist spy. When the authorities close in on Baslim, Thorby must ride with the Free Traders a league of merchant princes throughout the many worlds of a hostile galaxy, finding the courage to live by his wits and fight his way from society's lowest rung. But Thorby's destiny will be forever changed when he discovers the truth about his own identity...","fiction, young-adult, fantasy, paranormal, children",https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png,...,444,53,11250,4.0,NaN,-0.3818,POSITIVE,0.995149,0.995149,"{'neutral': 0.31399425864219666, 'anger': 0.28180813789367676, 'disgust': 0.2656250298023224, 'fear': 0.11125060170888901, 'sadness': 0.018206238746643066, 'surprise': 0.004642709624022245, 'joy': 0.004473037552088499}"
3,688299,0060541830,9780060541835,Congo,Michael Crichton,1980,0,"Deep in the African rain forest, near the legendary ruins of the Lost City of Zinj, an expedition of eight American geologists is mysteriously and brutally killed in a matter of minutes.\nTen thousand miles away, Karen Ross, the Congo Project Supervisor, watches a gruesome video transmission of the aftermath: a camp destroyed, tents crushed and torn, equipment scattered in the mud alongside dead bodies -- all motionless except for one moving image -- a grainy, dark, man-shaped blur.\nIn San Francisco, primatologist Peter Elliot works with Amy, a gorilla with an extraordinary vocabulary of 620 ""signs,"" the most ever learned by a primate, and she likes to fingerpaint. But recently, her behavior has been erratic and her drawings match, with stunning accuracy, the brittle pages of a Portuguese print dating back to 1642 . . . a drawing of an ancient lost city. A new expedition -- along with Amy -- is sent into the Congo where they enter a secret world, and the only way out may be through a horrifying death . . .","fiction, mystery, thriller, crime, fantasy, paranormal",https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png,...,14001,2926,136288,3.6,NaN,-0.9719,NEGATIVE,0.986794,-0.986794,"{'disgust': 0.5804082751274109, 'fear': 0.3399037718772888, 'anger': 0.02239895798265934, 'sadness': 0.02185998111963272, 'neutral': 0.01751544512808323, 'surprise': 0.017087072134017944, 'joy': 0.0008264894713647664}"
4,3464264,0451528824,9780451528827,Anne of Green Gables,L.M. Montgomery,1908,0,"Everyone's favorite redhead, the spunky Anne Shirley, begins her adventures at Green Gables, a farm outside Avonlea, Prince Edward Island. When the freckled girl realizes that the elderly Cuthberts wanted to adopt a boy instead, she begins to try to win them and, consequently, the reader, over.","fiction, young-adult, children, history, historical fiction, biography, romance",https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png,...,19933,9099,545418,4.2,NaN,0.8720,POSITIVE,0.923094,0.923094,"{'neutral': 0.6241617202758789, 'joy': 0.28834569454193115, 'disgust': 0.03454190492630005, 'anger': 0.03303816169500351, 'surprise': 0.00848483107984066, 'sadness': 0.008177867159247398, 'fear': 0.003249830100685358}"

In [18]:
### Convert emotion scores to separate columns for emotion and score.

In [19]:
### Convert values into lists. This will be expanded in Power BI

## Process the Reviews file

In [20]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143887 entries, 0 to 1143886
Data columns (total 10 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   review_id    1143887 non-null  object
 1   user_id      1143887 non-null  object
 2   work_id      1143887 non-null  int64
 3   started_at   796392 non-null   object
 4   read_at      1031765 non-null  object
 5   date_added   1143887 non-null  object
 6   rating       1106569 non-null  float64
 7   review_text  1143887 non-null  object
 8   n_votes      1143887 non-null  int64
 9   n_comments   1143887 non-null  int64
dtypes: float64(1), int64(3), object(6)
memory usage: 87.3+ MB

## Clean the Reviews table

In [21]:
reviews.head()

,review_id,user_id,work_id,started_at,read_at,date_added,rating,review_text,n_votes,n_comments
0,fa7a00c01296e3b2b2e857d79c51ea77,3693bb4f1062b659a354848cf11ca313,6128277,NaN,NaN,2013-12-21 00:00:00.000,5.0,"Fire is half-human and half monster. Monsters in these lands are beautiful, very bright and colorful and usually have a gift, and they destroy humans. Since half of Fire is human, she has to hide her beautiful red hair at all times and live heavily guarded. Her gift is that she can read and control minds. Because of her gift, she is useful at court. \n However, she is not well-received by the King and his brother. Fire's monster father played a heavy hand in the death of the previous king and they don't trust her. Fire may be half monster, but her humanity overcomes that part of her. She's kind and brave. \n In the beginning of Fire, we meet young Leek, who is quite unstable. He's a Graceling who has come through the mountains to the dells unexpectedly. He's cruel and manipulative and has a gift similar to Fire's; the gift of reading and controlling minds. His ambition will cause dissent with Fire and her world that will lead us to a compelling and twisting conclusion. \n Fire is a great fantasy adventure! The characters are well developed and the world is built in such a fantastic way that it's easy to follow and becomes believable. Magical creatures, great battles, political intrigue, a splash of romance, and supernatural abilities mesh so well together that you have a sure-fire hit! Kristin Cashore has done a remarkable job! Young adults and adults alike will enjoy this wonderful tale.",0,0
1,de0f7c8d15e247443e51969becf2878e,3693bb4f1062b659a354848cf11ca313,3270810,NaN,NaN,2013-12-21 00:00:00.000,5.0,"Katsa is a graceling - blessed with an ability (in her case, ability to kill easily) that marks her as different. Her uncle, the king, uses her as his personal enforcer, sending her out to hurt those who displease him. On one such trip, Katsa encounters a young man, a prince from a neighboring country, and after that, their fates will be entwined as she must learn to use her abilities compassionately and not as her Uncle's thug. But he has a secret grace and she will be drawn into politics of the world on a grand scale. \n This is a stand alone though there are two other books in this same world (one a prequel of sorts and the other a sequel but both with different characters). I did feel the book floats around quite a bit and lacks a good solid structure. As well, it can get tiring hearing Katsa echo the same thoughts over and over. Yes, we get the idea you don't want to marry. No, we don't need all the guys falling all over you even though you're supposedly deadly. And yes, we have a hero who is once again just a bit too good to be true.",0,0
2,e79b49504ef58b2defcdc8b79e2ec3fb,3693bb4f1062b659a354848cf11ca313,4768235,NaN,NaN,2013-12-19 00:00:00.000,5.0,"This is a fun, light-hearted read. Tammy Jo is having a bad week, a really bad week and despite her lack of magical abilities finds herself mixed up in more hocus-pocus than she can handle. And some of it is just plain funny. The humour is what makes the book worth reading. Tammy Jo has a sharp wit and her sarcasm is a joy to partake in. \n The book does feel a little chaotic at times, with Tammy Jo trying to accomplish multiple tasks at the same time, with no real understanding of what is going on around her. Plus, the world-building is a little on the slim side. But, all-in-all, it's a fun little ride. And while the whole werewolf mystery is cleared up, this is still very much a first book in a series. There are a number of threads left loose and a lot of unanswered or unaddressed questions. This left me feeling dissatisfied right at the end. \n I'm also at a bit of a loss about the Bryn/Zach situation. I like both men, despite their serious control issues (Zach especially). It's not quite a love triangle, but is too close to be comfortable. There's little chance of either one escaping unscathed and I find myself cringing at the prospects.",0,0
3,495c1210a9dbd819cbf7717dfb8b217f,3693bb4f1062b659a354848cf11ca313,6264661,NaN,NaN,2013-12-16 00:00:00.000,5.0,"Cassel, was a character that I was looking forward to and grew on me as the book grew to and end. He starts out as a criminal, and a thrifty conman. He was raised to believe in the con, and almost know what who had the upper hand. However, in the beginning you'll realize he's in college and away from his family. Which apparently is good for Cassel, his mother is out for whatever is best for her and her family and his brothers are trying to protect Cassel, even if they aren't going about it the best way. \n At first on the surface I thought the book was going to be about conmen and the thrifty lives they lead. However, I was wrong. The book is partially dealt with than conman lifestyles and than there is the Curse Workers lifestyle. Cruse Workers are different depending on what ""gift"" you have been given. In Cassel's mother's case it's emotion. She makes anyone feel how she needs to, to get the job done. There are those who can work memories and than those who can transform objects. Those who can transform are rare and the most sought after, however when one of the characters posses that ability the whole game changes. \n Cassell is different, he mourns the fact that he's not a curse worker at all, and in a family where everyone is a worker he's left alone. It also doesn't change the haunting nightmare he has every night, the dream of him killing his best friend and possibly first girlfriend. Furthermore I found that the second character I fell in love with was a White Cat that follows Cassell around and helps him along his journey. As Cassell, tries to figure out who he is supposed to find, and what's going on in his life, the White Cat remains by his side. \n I wanted more out of the world, and what it had to offer. I enjoyed the college school scenery and it made the school seem large and welcoming. However out in the world the only world and the only house that seemed worthwhile was the house that Cassel grew up in. The cluttered mess, and the worn down house gave a great backstory to Cassel that a few paragraphs could have explained. Yet how he got around was dumbed down to just driving his car from point A to point B. We see over and over Holly Black can create great worlds, so why doesn't she going from points to points. \n This book won't let you down, in fact it's a great read and a great relaxation piece. I was hooked immediately and if you are remotely interested, or sounds like something you might find interesting. I would almost garauntee that you'll enjoy this book. If you aren't hooked by the first chapter or two, I dunno what I will do, but I will find someone to make it up to you.",0,0
4,54fcd8963c9dd56485d2a4ad152699c2,3693bb4f1062b659a354848cf11ca313,3429537,NaN,NaN,2013-12-16 00:00:00.000,5.0,"This is kind of one of those books that I saw getting popular back with it first came out; many good reviews were popping up in the book community, and yet I continued to overlook it. I didn't even both to read the summary very closely. I was that certain I would dislike it based on the cover and title alone. In my defense, the title is a little misleading. It's different and makes the reader think that the book will be a light, quick vampire story. It was completely by chance that I saw it at a little used bookstore and decided to examine it more closely. To my great surprise, it actually sounded kind of interesting so I sat down and read the first few chapters. I continued to like it, so I bought it and stayed up half the night to finish. \n There was something seriously addicting about this novel; I never wanted to put it down, always very eager to see how it would end. So I guess I could say that my favorite thing about Jessica's Guide to Dating on the Dark Side would be the pacing. It's not on the short side, nor is it particularly long; rather, it tells exactly what it needs to and ends at a satisfying point. Though I did like how it ended, I'm still very excited to pick up the sequel and see what the author has in store for these people. \n Honestly, I loved Jessica's character. She was just a normal teenage girl in the start of the book, and of course she evolves by the end - what with finding out she's a vampire princess and all - but at the same time, she remains much the same in many ways. She reminded me a little of Meghan from the Iron Fey series; she, too, found out she was a princess (a faerie one, but still). Both of them grow up on a farm, as well. Jessica did have moments here and there where she acted kind of stupidly - though she stands up to her love interest a bit, she doesn't do it often enough. \n Lucius (I just recently learned how to pronounce his name, by the way) immediately had my attention from the first time he showed up. Of course, the reader is already aware of what he his and his purposes, but he changes throughout the book almost as much as Jessica does. He bounces back and forth between one extreme to the other, and I kind of felt like he should have a big hug. The chemistry with Jessica (a.k.a. Anastasia) definitely wasn't lacking; there are some steamy moments here, and they were well written and much appreciated. And the letters he writes to his uncle are hilarious. Fantaskey's version of a vampire was interesting. I like the way she built her world with the royalty aspect, but at the same time, I'm confused about how the undead can have children (but then, I'm still confused about that aspect of Twilight, so.). \n I wasn't extremely fond of the side characters - I've heard that Mindy starts narrating some of the time in Jessica Rules the Dark Side, and I have to admit that I was none too thrilled with that. She was an okay character, but I'm not so sure I want to see the story through her eyes. I did, however, enjoy the relationship Jessica had with her parents, and the conflicts brought about by Faith and Jake. I was pretty surprised by the novel took towards the end - I don't want to spoil anything, but I'll say I was surprised that who I thought would be the main villain of the book turned out not to be. Overall, I'm just going to go with the classic saying - don't judge a book by its cover (or its title, for that matter), because I'm really glad I picked this up.",0,0

In [22]:
# We will drop the user_id column, as it is not any use we just have a number and no names.
reviews.drop([
    "user_id","review_id"], 
    axis=1, 
    inplace=True
)

In [23]:
reviews["started_at"] = pd.to_datetime(reviews["started_at"], errors="coerce").dt.date
reviews["read_at"] = pd.to_datetime(reviews["read_at"], errors="coerce").dt.date
reviews["date_added"] = pd.to_datetime(reviews["read_at"], errors="coerce").dt.date

In [24]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143887 entries, 0 to 1143886
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   work_id      1143887 non-null  int64
 1   started_at   796391 non-null   object
 2   read_at      1031763 non-null  object
 3   date_added   1031763 non-null  object
 4   rating       1106569 non-null  float64
 5   review_text  1143887 non-null  object
 6   n_votes      1143887 non-null  int64
 7   n_comments   1143887 non-null  int64
dtypes: float64(1), int64(3), object(4)
memory usage: 69.8+ MB

In [25]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [26]:
%%time
# Create Vader Sentiment Score
analyzer=SentimentIntensityAnalyzer()

# define a function to get the score
def get_sentiment(text):
    return analyzer.polarity_scores(text)['compound']

CPU times: total: 15.6 ms
Wall time: 13.4 ms

In [27]:
# apply the function
reviews['sentiment'] = reviews['review_text'].apply(get_sentiment)

In [28]:
%%time
# Now do a sentiment analysis using NLP

from transformers import pipeline, logging

logging.set_verbosity_error() # Turn off logging except for major errors

sentiment_analyzer = pipeline("sentiment-analysis",
                              model="distilbert/distilbert-base-uncased-finetuned-sst-2-english",                              
                              device='cuda', # Use GPU
                              force_download=True,
                              truncation=True) # adding truncation here to truncate text before analyzing sentiment

sentiment_scores = works['description'].apply(sentiment_analyzer) # Apply the Analyser

# extract the label and score and create a sentiment score for all books
reviews['label_hf'] = sentiment_scores.apply(lambda x: x[0]['label'])
reviews['score_hf'] = sentiment_scores.apply(lambda x: x[0]['score'])

# This applys a negative value for a negative sentiment
reviews['sentiment_hf'] = reviews.apply(lambda row: row['score_hf'] if row['label_hf'] == 'POSITIVE' else -row['score_hf'], axis=1)

C:\Users\andrew\anaconda3\envs\nlp_transformers\Lib\site-packages\huggingface_hub\file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

CPU times: total: 3min 54s
Wall time: 3min 57s

### Write the reviews data frame to a MySql table

In [29]:
engine = create_engine('mysql+pymysql://root:$H0nggh0ri*@localhost:3306/mavenbookshelf')

In [30]:
reviews.to_sql('reviews', con=engine, if_exists='replace', index=False)

1143887

In [30]:
%%time
from transformers import pipeline

# Load emotion classification pipeline
emotion_pipeline = pipeline(
    "text-classification",
    model="j-hartmann/emotion-english-distilroberta-base",
    tokenizer="j-hartmann/emotion-english-distilroberta-base",
    force_download=True,
    top_k=None,
    truncation=True,
    max_length=512
)


# Apply to your dataset
def get_emotion_scores(text):
    scores = emotion_pipeline(text)[0]
    return {item['label']: item['score'] for item in scores}

reviews['emotion_scores'] = reviews['review_text'].apply(get_emotion_scores)

C:\Users\andrew\anaconda3\envs\nlp_transformers\Lib\site-packages\huggingface_hub\file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

CPU times: total: 13h 37min 54s
Wall time: 12h 30min 50s

KeyboardInterrupt


KeyboardInterrupt

In [ ]:
reviews.head()